<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="NBLAP105" name="Test" tests="1" failures="1" timestamp="20 Mar 2017 10:33:48 GMT" time="4.17" errors="0">
  <testcase name="dataFromDbTest" time="4.138" classname="com.db_dataDrivenTest.db_data.DataFromDb">
    <failure type="java.sql.SQLException" message="Operation not allowed after ResultSet closed">
      <![CDATA[java.sql.SQLException: Operation not allowed after ResultSet closed
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:996)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:935)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:924)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:870)
	at com.mysql.jdbc.ResultSetImpl.checkClosed(ResultSetImpl.java:734)
	at com.mysql.jdbc.ResultSetImpl.next(ResultSetImpl.java:6313)
	at com.db_dataDrivenTest.db_data.DataFromDb.dataFromDbTest(DataFromDb.java:14)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- dataFromDbTest -->
</testsuite> <!-- Test -->
